using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Xml;
using System.Xml.Linq;

namespace AutoStart {
    public class FileWriter {
        FilesManager filesManager;

        string programsFile;
        string idFile;

        public FileWriter () {
            filesManager = new FilesManager();

            programsFile = filesManager.programsFile;
            idFile = filesManager.idFile;
        }

        public void WriteProgramsFileStart (XmlWriter writer) {
            //Write all starting text and create element
            writer.WriteStartDocument();
            writer.WriteComment("All programs used by AutoStarter, please do NOT edit this file!");

            writer.WriteStartElement("Programs");
            writer.WriteEndElement();
            writer.WriteEndDocument();

            writer.Flush();
            writer.Close();
        }

        public void WriteIDFileStart() {
            //Handle file creation and write first id: 0;
            File.WriteAllText(idFile, "0");
        }

        public void WriteProgramsRow(String path, int id, String name, XDocument doc, XElement programsRow) {
            programsRow.Add(new XElement("Program", new XAttribute("id", id),
                       new XElement("path", path),
                       new XElement("name", name)));
            doc.Save(programsFile);
        }

        public void NextID (int id) {
            File.WriteAllText(idFile, (id).ToString());
        }
    }
}
